author: ${project.authors}
name: ${project.name}
version: ${project.version}
softdepend: ${project.softdepends}
main: ${project.main}
database: true

commands:
  sethome:
    usage: /<command> [<name>]
    permission: telewarp.commands.home
  delhome:
    usage: /<delhome> [<name>]
    permission: telewarp.commands.home
  tpa:
    permission: telewarp.commands.tpa
    usage: /<command> <player>
  tpahere:
    permission: telewarp.commands.tpahere
    usage: /<command> <player>
  tpayes:
    permission: telewarp.commands.tpa
    usage: /<command>
  tpano:
    permission: telewarp.commands.tpa
    usage: /<command>
  homes:
    permission: telewarp.commands.home
    usage: /<command>
  home:
    aliases: [h]
    permission: telewarp.commands.home
    usage: /<command>
  warp:
    permission: telewarp.commands.warp
    usage: /<command> <warp>
  warps:
    permission: telewarp.commands.warp
    usage: /<command> [<page>]
  back:
    permission: telewarp.commands.back
    usage: /<command>
  delwarp:
    permission: telewarp.admin
    usage: /<command> <warp>
  setwarp:
    permission: telewarp.admin
    usage: /<command> <warp> [<cost>] [<description...>]
  telewarp:
    aliases: [tw]
    permission: telewarp.admin
    usage:
      - "/<command> [reload|save]"
      - "/<command> resetcooldown <player>"

permissions:
  telewarp.admin:
    default: op
    children:
      telewarp.commands.home.others: true
      telewarp.commands.tp: true
      telewarp.commands.tpa: true
      telewarp.commands.home: true
      telewarp.commands.warp: true
      telewarp.commands.back: true
      telewarp.commands.back.ondeath: true
      telewarp.commands.smoke: true
      telewarp.signs.create: true
      telewarp.signs.use: true
      telewarp.nocost.*: true
      telewarp.nowarmup.*: true
      
  telewarp.nowarmup.*:
    default: op
    children: 
      telewarp.nowarmup.warp: true
      telewarp.nowarmup.home: true
      telewarp.nowarmup.tpa: true
      telewarp.nowarmup.back: true
      telewarp.nowarmup.tp: true
  
  telewarp.nocost.*:
      default: op
      children: 
        telewarp.nocost.warp: true
        telewarp.nocost.home: true
        telewarp.nocost.tpa: true
        telewarp.nocost.back: true
        telewarp.nocost.tp: true
  
  telewarp.halfwarmup.*:
      default: false
      children: 
        telewarp.halfwarmup.warp: true
        telewarp.halfwarmup.home: true
        telewarp.halfwarmup.tpa: true
        telewarp.halfwarmup.back: true
        telewarp.halfwarmup.tp: true
    
    telewarp.halfcost.*:
        default: false
        children: 
          telewarp.halfcost.warp: true
          telewarp.halfcost.home: true
          telewarp.halfcost.tpa: true
          telewarp.halfcost.back: true
          telewarp.halfcost.tp: true
    
    
        
  telewarp.commands.home.others:
    default: op
  telewarp.signs.create:
    default: op
  telewarp.signs.use:
    default: true
  telewarp.commands.tp:
    default: op
  telewarp.commands.tpa:
    default: true
  telewarp.commands.tpahere:
    default: true
  telewarp.commands.home:
    default: true
  telewarp.commands.warp:
    default: true
  telewarp.commands.back:
    default: op
  telewarp.commands.back.ondeath:
    default: op
  telewarp.nocost.home:
    default: op
  telewarp.nowarmup.home:
    default: op
  telewarp.nocost.back:
    default: op
  telewarp.nowarmup.back:
    default: op
  telewarp.nocost.warp:
    default: op
  telewarp.nowarmup.warp:
    default: op
  telewarp.nocost.tpa:
    default: op
  telewarp.nowarmup.tpa:
    default: op
  telewarp.nocost.tp:
    default: op
  telewarp.nowarmup.tp:
    default: op
  telewarp.halfcost.home:
    default: false
  telewarp.halfwarmup.home:
    default: false
  telewarp.halfcost.back:
    default: false
  telewarp.halfwarmup.back:
    default: false
  telewarp.halfcost.warp:
    default: false
  telewarp.halfwarmup.warp:
    default: false
  telewarp.halfcost.tpa:
    default: false
  telewarp.halfwarmup.tpa:
    default: false
  telewarp.halfcost.tp:
    default: false
  telewarp.halfwarmup.tp:
    default: false
    
  telewarp.confusionimmunity:
    default: false
  telewarp.smoke:
    default: op